### ISSUE TITLE
SEVERE: Adb rejected adb port forwarding command: cannot bind to socket

### ISSUE THREAD

**Issue by bunnyhopping** [ns130291/MonkeyRemote#9]
com.android.ddmlib.AdbCommandRejectedException: cannot bind to socket
        at com.android.ddmlib.AdbHelper.createForward(AdbHelper.java:767)
        at com.android.ddmlib.Device.createForward(Device.java:688)
        at com.android.chimpchat.adb.AdbChimpDevice.createManager(AdbChimpDevice.java:125)
        at com.android.chimpchat.adb.AdbChimpDevice.<init>(AdbChimpDevice.java:71)
        at com.android.chimpchat.adb.AdbBackend.waitForConnection(AdbBackend.java:122)
        at com.android.chimpchat.ChimpChat.waitForConnection(ChimpChat.java:91)
        at de.nsvb.monkeyremote.MonkeyRemote.main(MonkeyRemote.java:102)

Exception in thread "main" java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
        at com.android.chimpchat.adb.AdbChimpDevice.<init>(AdbChimpDevice.java:73)
        at com.android.chimpchat.adb.AdbBackend.waitForConnection(AdbBackend.java:122)
        at com.android.chimpchat.ChimpChat.waitForConnection(ChimpChat.java:91)
        at de.nsvb.monkeyremote.MonkeyRemote.main(MonkeyRemote.java:102)

**Comment by bunnyhopping** [comment]
C:\Program Files (x86)\Java\jre1.8.0_251\bin>java -jar MonkeyRemote-0.4.jar "PATH TO ADB EXECUTABLE" 0.5   
This is the CMD command I used

**Comment by bunnyhopping** [comment]
C:\Program Files (x86)\Java\jre1.8.0_251\bin>java -jar MonkeyRemote-0.4.jar "C:\adb\adb.exe" 0.5
Jun 18, 2020 8:00:07 PM com.android.chimpchat.adb.AdbChimpDevice createManager
SEVERE: Adb rejected adb port forwarding command: cannot bind to socket
com.android.ddmlib.AdbCommandRejectedException: cannot bind to socket
        at com.android.ddmlib.AdbHelper.createForward(AdbHelper.java:767)
        at com.android.ddmlib.Device.createForward(Device.java:688)
        at com.android.chimpchat.adb.AdbChimpDevice.createManager(AdbChimpDevice.java:125)
        at com.android.chimpchat.adb.AdbChimpDevice.<init>(AdbChimpDevice.java:71)
        at com.android.chimpchat.adb.AdbBackend.waitForConnection(AdbBackend.java:122)
        at com.android.chimpchat.ChimpChat.waitForConnection(ChimpChat.java:91)
        at de.nsvb.monkeyremote.MonkeyRemote.main(MonkeyRemote.java:102)

Exception in thread "main" java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
        at com.android.chimpchat.adb.AdbChimpDevice.<init>(AdbChimpDevice.java:73)
        at com.android.chimpchat.adb.AdbBackend.waitForConnection(AdbBackend.java:122)
        at com.android.chimpchat.ChimpChat.waitForConnection(ChimpChat.java:91)
        at de.nsvb.monkeyremote.MonkeyRemote.main(MonkeyRemote.java:102)

**Comment by ns130291** [comment]
Does a normal adb connection work?
